version: 2

jobs:
  "Execute tests on Ubuntu":
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
    docker:
      - image: fastlanetools/fastlane:2.3.4
    steps:
      - checkout

      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
          paths:
            - .bundle
  build:
    macos:
      xcode: "10.1.0"
    environment:
      FL_OUTPUT_DIR: output
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-homebrew-{{ epoch }}
            - v2-homebrew
      - restore_cache:
          keys:
            - v3-rbenv-{{ checksum "Gemfile" }}
            - v3-rbenv-2.6.1
            - v3-rbenv
      - run:
          name: Setup Build
          command: |
            brew uninstall chruby
            brew install rbenv ruby-build
            echo 'eval "$(rbenv init -)"' > ~/.bash_profile
            echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bash_profile
            source ~/.bash_profile
            cat ~/.bash_profile
            which ruby
            ruby -v
#  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
#            brew install chruby
      - save_cache:
          key: v2-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew

      - run:
          name: Setup Build
          command: |
            rbenv install 2.6.1 -s
            rbenv rehash
            rbenv global 2.6.1
            source ~/.bash_profile
            gem install bundler
            gem update --system
            rbenv rehash
            which ruby
            ruby -v
      - save_cache:
          key: v3-rbenv-2.6.1
          paths:
            - ~/.rbenv

      - run:
          name: Setup Build
          command: |
            source ~/.bash_profile 
            echo "2.6.1" > .ruby-version
            which ruby
            ruby -v
            bundler -v
            bundle install --binstubs
            bundle check || bundle install
      - save_cache:
          key: v3-rbenv-{{ checksum "Gemfile" }}
          paths:
            - ~/.rbenv

      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

      # - run:
      #     name: Check PR Metadata
      #     command: bundle exec danger || echo "danger failed"

      # - restore_cache:
      #     key: v1-{{ arch }}-rubocop

      # - run: bundle exec fastlane execute_tests

      # - save_cache:
      #     key: v1-{{ arch }}-rubocop
      #     paths:
      #       - ~/.cache/rubocop_cache
      # - store_test_results:
      #     path: ~/test-reports
      # - store_artifacts:
      #     path: ~/test-reports/rspec
      #     destination: test-reports

      # - run:
      #     name: Post Test Results to GitHub
      #     command: bundle exec danger || echo "danger failed"
      #     when: always # Run this even when tests fail
workflows:
  version: 2
  build:
    jobs:
      - build
      # - "Execute tests on Ubuntu"
